apps/cliente/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from apps.cliente.views import *
from django.contrib.auth.decorators import login_required

app_name = 'Clientes'

urlpatterns = [
    path('lista', login_required(lista.as_view()), name='lista'),
    path('nuevo', login_required(CrudView.as_view()), name='nuevo'),
]

whatsappmasive/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cliente/', include('apps.cliente.urls', namespace='cliente')),
    path('send/', include('apps.whatsapp.urls', namespace='whatsapp')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
                  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cliente/models.py
from datetime import datetime

from django.db import models
from django.forms import model_to_dict

from whatsappmasive.settings import MEDIA_URL

SEXO = (
    (1, 'Masculino'),
    (0, 'Femenino'),
)


class Cliente(models.Model):
    nombres = models.CharField(max_length=50)
    telefono = models.CharField(max_length=13, unique=True)
    fecha = models.DateField(default=datetime.now)

    def __str__(self):
        return '{} '.format(self.nombres)

    def toJSON(self):
        item = model_to_dict(self)
        item['fecha'] = self.fecha.strftime('%d/%m/%Y')
        return item

    class Meta:
        db_table = 'cliente'
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'
        ordering = ['-nombres']


class Filexls(models.Model):
    archivo = models.FileField(upload_to='files/%Y/%m/%d', null=True, blank=True)

    # def __str__(self):
    #     return '{} '.format(self.archivo.path)
    #
    # def get_file(self):
    #     if self.archivo:
    #         return '{}{}'.format(MEDIA_URL, self.archivo)

    def toJSON(self):
        item = model_to_dict(self)
        # item['archivo'] = self.get_file()
        return item

    class Meta:
        db_table = 'archivo'
        verbose_name = 'archivo'
        verbose_name_plural = 'archivos'
        ordering = ['-archivo']

apps/cliente/forms.py
from datetime import *

from django import forms
from django.forms import TextInput

from .models import Cliente, Filexls


class ClienteForm(forms.ModelForm):
    # constructor
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        this_year = datetime.now().year
        years = range(this_year - 15, this_year - 3)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

            self.fields['nombres'].widget = TextInput(
                attrs={'placeholder': 'Ingrese sus dos nombres', 'class': 'form-control form-rounded'})

            self.fields['telefono'].widget = TextInput(
                attrs={'placeholder': 'Ingrese numero de telefono', 'class': 'form-control form-rounded'})
        # habilitar, desabilitar, y mas

    class Meta:
        model = Cliente
        fields = ['nombres', 'telefono']
        labels = {'nombres': 'Nombres', 'Telefono': 'Celular'}
        widgets = {'nombres': forms.TextInput(), 'telefono': forms.TextInput()}


class FileForm(forms.ModelForm):

    class Meta:
        model = Filexls
        fields = ['archivo']
        labels = {'archivo': 'Archivo'}

apps/cliente/views.py
import json

from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import *

from apps.cliente.forms import ClienteForm, FileForm
from apps.cliente.models import Cliente
import pandas as pd

opc_icono = 'fa fa-user'
opc_entidad = 'Clientes'
crud = '/cliente/nuevo'


class lista(ListView):
    model = Cliente
    template_name = "cliente_list.html"
    permission_required = 'cliente.view_cliente'

    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'list':
                data = []
                for c in Cliente.objects.all():
                    data.append(c.toJSON())
            elif action == 'search':
                data = []
                term = request.POST['term']
                query = Cliente.objects.filter(
                    Q(nombres__icontains=term) | Q(apellidos__icontains=term) | Q(cedula__icontains=term))[0:10]
                for a in query:
                    item = a.toJSON()
                    item['text'] = a.get_full_name()
                    data.append(item)
            else:
                data['error'] = 'No ha seleccionado una opcion'
        except Exception as e:
            data['error'] = 'No ha seleccionado una opcion'
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['icono'] = opc_icono
        data['entidad'] = opc_entidad
        data['boton'] = 'Nuevo Cliente'
        data['titulo'] = 'Listado de Clientes'
        data['form'] = ClienteForm
        data['form_file'] = FileForm
        data['nuevo'] = '/cliente/nuevo'
        return data


class CrudView(TemplateView):
    form_class = ClienteForm
    template_name = 'cliente_form.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        action = request.POST['action']

        try:
            if action == 'add':
                f = ClienteForm(request.POST)
                data = self.save_data(f)
            if action == 'file':
                f = FileForm(request.POST, request.FILES)
                if f.is_valid():
                    var = f.save()
                    num = pd.read_excel(var.archivo.path)
                    data_dict = num.to_dict('list')
                    celulares = data_dict['celular']
                    key_to_lookup = 'nombre'
                    if key_to_lookup in data_dict:
                        nombres = data_dict['nombre']
                        combo = zip(nombres, celulares)
                        for nombre, celular in combo:
                            c = Cliente()
                            c.nombres = nombre
                            c.telefono = '+'+str(celular)
                            c.save()
                    else:
                        for numero in celulares:
                            c = Cliente()
                            c.nombres = 'Sin nombre'
                            c.telefono = '+'+str(numero)
                            c.save()
                else:
                    data['error'] = f.errors
            elif action == 'edit':
                pk = request.POST['id']
                cliente = Cliente.objects.get(pk=int(pk))
                f = ClienteForm(request.POST, instance=cliente)
                data = self.save_data(f)
            elif action == 'delete':
               pk = request.POST['id']
               cli = Cliente.objects.get(pk=pk)
               cli.delete()
               data['resp'] = True
            else:
                data['error'] = 'No ha seleccionado ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return HttpResponse(json.dumps(data), content_type='application/json')

    def save_data(self, f):
        data = {}
        if f.is_valid():
            f.save()
        else:
            data['error'] = f.errors
        return data

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{{ titulo }}</title>
  <!-- Tell the browser to be responsive to screen width -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
 <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'css/adminlte.min.css'%}">
  <link rel="stylesheet" href="{% static 'css/adminlte.css'%}">
 <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"
            crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet"/>
    <link href="{% static "lib/daterangepicker-3.1/daterangepicker.css" %}" rel="stylesheet">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->
{% include 'header.html' %}
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
{#{% include 'sidebar.html' %}#}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
      <input type="hidden" name="user_tipo" value="{{ request.user.tipo }}">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark"><i class="fas fa-greater-than"></i> <i class="{{ icono }}"></i> {{entidad}}</h1>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      {% block content %}


      {% endblock %}

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->


  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{#<script src="{% static 'lib/jquery/jquery.js' %}"></script>#}
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'lib/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>

<!-- Bootstrap 4 -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<!-- ChartJS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<!-- daterangepicker -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script src="{% static "lib/daterangepicker-3.1/spanish.js" %}"></script>
<script src="{% static "lib/daterangepicker-3.1/daterangepicker.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'js/adminlte.js' %}"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
{#<script src="{% static 'lib*datatables/jquery.dataTables.js' %}"></script>#}
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
<script src="{% static 'lib/bootstrap-touchspin-4.3.0/jquery.bootstrap-touchspin.js' %}"></script>
<script src="{% static 'apps/funtions.js' %}"></script>
<script>
    $('[data-toggle="tooltip"]').tooltip();
</script>
{% block script %}

{% endblock %}
{% block extra %}
{% endblock %}
{% block javascript %}

{% endblock %}
</body>
</html>

templates/cliente_form.html
{% extends 'form.html' %}
{% load static %}
{% block extra %}
    <script src="{% static 'apps/cliente/cliente.js' %}"></script>
{% endblock %}

templates/cliente_list.html
{% extends 'list.html' %}
{% load static %}
{% block table %}
    <thead>
    <tr>
        <th style="width: 5%">Id</th>
        <th style="width: 15%">Nombres</th>
        <th style="width: 10%">Telefono</th>
        <th class="text-center" style="width: 10%"><em class="fa fa-cog"></em></th>
    </tr>
    </thead>
    <tbody>
    </tbody>
{% endblock %}

{% block extra %}
    <script src="{% static 'apps/cliente/cliente_list.js' %}"></script>
    <script src="{% static 'apps/cliente/cliente.js' %}"></script>
    <script>
        function validaNumericos(event) {
            console.log(event.charCode);
            if (event.charCode >= 48 && event.charCode <= 57 || event.charCode === 43) {
                return true;
            }
            return false;
        }
    </script>
{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="{% static 'lib/bootstrap-touchspin-4.3.0/jquery.bootstrap-touchspin.css' %}"/>
{% endblock %}
{% block content %}
    <style>
        .btn-space {
            margin-right: 5px !important;
        }
    </style>
    <!-- BASIC FORM ELELEMNTS -->
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h5><i class="fas fa-folder-plus"></i> {{ titulo }}</h5>

                </div>
                <div class="card-body">
                    <div class="form">
                        <form class="cmxform form-horizontal style-form" id="form" method="POST" action="{{ crud }}">
                            <input type="hidden" id="action" name="action" value="{{ action }}">
                            <input type="hidden" id="indice" name="indice" value="{{ empresa.indice }}">
                            <input type="hidden" id="iva" name="iva" value="{{ empresa.iva }}">
                            <input type="hidden" name="option" value="{{ option }}">
                            {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                            {% for field in form.visible_fields %}

                                <div class="form-group col-lg-12">
                                    <label style="font-size: 13px;"
                                           class="col-lg-3 control-label"><strong>{{ field.label }}:</strong></label>
                                    <label class="badge bg-important">{{ field.errors }}</label>
                                    <div class="col-lg-10">
                                        {% csrf_token %}
                                        {{ form.media }}
                                        {{ field }}
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <button class="btn btn-success btn-sm" type="submit"><i
                                            class="fa fa-save"></i> {{ boton }}
                                    </button>
                                    <a type="button" class="btn btn-danger btn-sm" style="color:white;" id="reload"
                                       onclick=" window.history.back();">
                                        <i class="fas fa-times"></i> Cancelar
                                    </a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
            <!-- /form-panel -->
        </div>
        <!-- /col-lg-12 -->
    </div>
    <!-- /row -->
{% endblock %}
{% block script %}
    <script src=" https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/additional-methods.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/additional-methods.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    <script src="{% static 'lib/bootstrap-touchspin-4.3.0/jquery.bootstrap-touchspin.js' %}"></script>
{% endblock %}

templates/header.html
 <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Menu Principal</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="fa fa-cogs"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">Configuracion</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fa fa-user"></i> Perfil de Usuario
          </a>
            {% if request.user.tipo == 1 %}
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
             <i class="fa fa-cogs"></i> Configuracion de datos de empresa
          </a>
            {% endif %}
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-sign-out-alt"></i> Salir
          </a>
        </div>
      </li>
    </ul>
  </nav>

templates/list.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet"/>
    <link href="https://nightly.datatables.net/searchpanes/css/searchPanes.dataTables.min.css" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/searchpanes/1.1.1/css/searchPanes.dataTables.min.css" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/select/1.3.1/css/select.dataTables.min.css" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/responsive/2.2.5/css/responsive.dataTables.min.css" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.bootstrap.min.css" rel="stylesheet"/>

{% endblock %}
{% block content %}
    <!-- BASIC FORM ELELEMNTS -->
    {% block elements %}

    {% endblock %}
    <div class="container col-lg-12">
        <div class="row">
            <div class="col-md-12">
                <div class="panel">
                    <div class="panel-body">
                        <table id="datatable" class="table table-bordered table-hover" style="width: 100%">
                            {% block table %}

                            {% endblock %}
                        </table>
                    </div>
                    {% block botones %}
                        <div class="panel-footer">
                            <br>
                            <a type="button" class="btn btn-primary btn-sm" id="nuevo" style="color: white">
                                <i class="fa fa-plus" aria-hidden="true"></i> {{ boton }}
                            </a>
                             <a type="button" class="btn btn-success btn-sm" id="archivo" style="color: white">
                                <i class="fa fa-file-excel" aria-hidden="true"></i> Archivo XLS
                            </a>
                            <a type="button" class="btn btn-default btn-sm" id="reload"
                               onclick=" location.reload();">
                                <i class="fas fa-sync-alt"></i> Actualizar
                            </a>
                        </div>
                    {% endblock %}

                </div>
            </div>
        </div>
    </div>
    {% block modal %}
        <div class="modal fade" id="Modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <form method="post" id="form" enctype="multipart/form-data" action=".">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel"><i class="fas fa-plus"></i>&nbsp;{{ titulo_new }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="container-fluid">
                            <div class="form-group">
                                <label for="id_nombres">{{ form.nombres.label_tag }}</label>
                                {{ form.nombres }}
                            </div>
                             <div class="form-group">
                                <label for="id_telefono">{{ form.telefono.label_tag }}</label>
                                <input type="text" name="telefono" placeholder="Ingrese numero de telefono" class="form-control form-rounded" required="" id="id_telefono"
                                onkeypress='return validaNumericos(event)'>
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <a type="button" class="btn btn-danger" data-dismiss="modal"  onclick=" reset();"
                           style="color: white"><i class="fas fa-times" ></i> Cancelar
                        </a>
                        <button type="submit" class="btn btn-primary"><i class="far fa-save"></i>&nbsp;Guardar
                        </button>
                    </div>
                </div>
            </div>
        </form>

    </div>
        <div class="modal fade" id="Modal_file" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <form method="post" id="form_file" enctype="multipart/form-data" action=".">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel"><i class="fas fa-plus"></i>&nbsp;Subir Archivo XLS</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="container-fluid">
                            <div class="form-group">
                               {{ form_file.as_p }}
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <a type="button" class="btn btn-danger" data-dismiss="modal"  onclick=" reset();"
                           style="color: white"><i class="fas fa-times" ></i> Cancelar
                        </a>
                        <button type="submit" class="btn btn-primary"><i class="far fa-save"></i>&nbsp;Guardar
                        </button>
                    </div>
                </div>
            </div>
        </form>

    </div>

    {% endblock %}
{% endblock %}
{% block script %}
    <script src="https://cdn.datatables.net/searchpanes/1.1.1/js/dataTables.searchPanes.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/select/1.3.1/js/dataTables.select.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.bootstrap.min.js"></script>
    <script type="text/javascript"
            src="https://cdn.datatables.net/responsive/2.2.5/js/dataTables.responsive.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>
    <script src=" https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/additional-methods.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/additional-methods.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.4/js/buttons.print.min.js"></script>
{% endblock %}

templates/mensaje_form.html
{% extends 'form.html' %}
{% load static %}
{% block extra %}
    <script src="{% static 'apps/mensaje.js' %}"></script>
{% endblock %}